// Part 2 of Hazelcast features - remaining categories

export const hazelcastFeaturesPartTwo = {
  'JET PIPELINE MANAGEMENT': [
    {
      name: 'Jet Pipeline Designer with DAG view',
      desc: 'Visual pipeline designer with directed acyclic graph representation',
      moscow: 'Must-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Expand to EMEA',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 5,
      technicalComplexity: 5,
      effortRequired: 5
    },
    {
      name: 'Draggable pipeline nodes',
      desc: 'Drag and drop interface for pipeline node arrangement',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Pipeline editor with visual design',
      desc: 'Rich visual editor for pipeline creation and modification',
      moscow: 'Must-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 5,
      effortRequired: 5
    },
    {
      name: 'Pipeline creation and modification',
      desc: 'Complete lifecycle management for Jet pipelines',
      moscow: 'Must-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Expand to EMEA',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 5,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Real-time pipeline monitoring',
      desc: 'Live monitoring of pipeline execution and performance',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    }
  ],
  'DEVELOPER TOOLS': [
    {
      name: 'SQL Browser with query execution',
      desc: 'Interactive SQL browser for database queries and exploration',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Developer Console',
      desc: 'Terminal-style interface for advanced development tasks',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Code execution environment',
      desc: 'Safe environment for executing code snippets and scripts',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 5,
      effortRequired: 5
    },
    {
      name: 'Database interaction capabilities',
      desc: 'Direct database interaction tools and utilities',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ],
  'BUSINESS INTELLIGENCE': [
    {
      name: 'BI dashboard with analytics',
      desc: 'Comprehensive business intelligence dashboard with advanced analytics',
      moscow: 'Should-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 5,
      effortRequired: 5
    },
    {
      name: 'Custom dashboard builder',
      desc: 'Tool for users to create and customize their own dashboards',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 5,
      effortRequired: 5
    },
    {
      name: 'Saved dashboards management',
      desc: 'Save, load, and manage custom dashboard configurations',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Widget-based dashboard system',
      desc: 'Modular widget system for flexible dashboard composition',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Data visualization tools',
      desc: 'Advanced charting and visualization capabilities',
      moscow: 'Should-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    }
  ],
  'INTEGRATIONS': [
    {
      name: 'ServiceNow integration dashboard',
      desc: 'Integration with ServiceNow for incident and change management',
      moscow: 'Should-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Expand to EMEA',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Business Intelligence integration',
      desc: 'Connect with external BI tools and platforms',
      moscow: 'Could-Have',
      targetQuarter: 'Q4 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Prometheus integration',
      desc: 'Integration with Prometheus for metrics and monitoring',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Third-party service connectivity',
      desc: 'Generic framework for connecting to external services',
      moscow: 'Could-Have',
      targetQuarter: 'Q4 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 5,
      effortRequired: 5
    },
    {
      name: 'Enterprise integration management',
      desc: 'Comprehensive enterprise integration capabilities',
      moscow: 'Could-Have',
      targetQuarter: 'Q4 2026',
      tshirtSize: 'XL',
      state: 'Missing',
      goal: 'Expand to EMEA',
      gapTypes: ['Process'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 5,
      effortRequired: 5
    }
  ],
  'DEMO DASHBOARDS': [
    {
      name: 'Flight Operations Dashboard',
      desc: 'Demo dashboard showing flight operations with live charts',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Documentation/Training'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 4
    },
    {
      name: 'High-Frequency Trading Dashboard',
      desc: 'Demo dashboard for HFT scenarios with real-time data',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Documentation/Training'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Industrial IoT Dashboard',
      desc: 'Demo dashboard for IoT use cases with sensor monitoring',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Documentation/Training'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 4
    },
    {
      name: 'How Hazelcast Works sections',
      desc: 'Educational content explaining Hazelcast concepts and architecture',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Documentation/Training'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 2,
      effortRequired: 3
    },
    {
      name: 'Industry-specific demonstrations',
      desc: 'Use case demonstrations for different industry verticals',
      moscow: 'Could-Have',
      targetQuarter: 'Q4 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Expand to EMEA',
      gapTypes: ['Documentation/Training'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 4
    }
  ],
  'PARTITION MANAGEMENT': [
    {
      name: 'Partition detail view',
      desc: 'Detailed view of partitions with clickable interface',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Partition distribution tracking',
      desc: 'Monitor how partitions are distributed across cluster members',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Backup partition management',
      desc: 'Manage and monitor backup partitions across the cluster',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Partition migration monitoring',
      desc: 'Monitor partition migrations during cluster changes',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ]
};
