// Part 3 of Hazelcast features - final categories

export const hazelcastFeaturesPartThree = {
  'AI ASSISTANCE': [
    {
      name: 'Fixed AI Assistant button',
      desc: 'Persistent AI assistant interface with context-aware help',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Context-aware help system',
      desc: 'Intelligent help system that provides contextual assistance',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Navigation assistance',
      desc: 'AI-powered navigation help and guided tours',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ],
  'DIAGNOSTIC TOOLS': [
    {
      name: 'Health check monitoring',
      desc: 'Comprehensive health monitoring for cluster and members',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 5,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Diagnostic logging with filtering',
      desc: 'Advanced logging system with filtering and search capabilities',
      moscow: 'Should-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'System status verification',
      desc: 'Automated system status checks and verification tools',
      moscow: 'Should-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Performance diagnostics',
      desc: 'Tools for diagnosing performance issues and bottlenecks',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    }
  ],
  'ALERTING & LOGGING': [
    {
      name: 'Alert management system',
      desc: 'Comprehensive alert configuration and management',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Reduce Churn by 5%',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 5,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Log viewer with filtering',
      desc: 'Advanced log viewing interface with powerful filtering options',
      moscow: 'Should-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Real-time alert notifications',
      desc: 'Live notification system for critical alerts and events',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Reduce Churn by 5%',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 5,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Historical log analysis',
      desc: 'Tools for analyzing historical log data and trends',
      moscow: 'Could-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    }
  ],
  'CONFIGURATION': [
    {
      name: 'Settings management',
      desc: 'Centralized settings and configuration management interface',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Cluster configuration options',
      desc: 'Interface for configuring cluster-wide settings and parameters',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'User preferences',
      desc: 'Personal user preferences and customization options',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'S',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 2,
      effortRequired: 2
    },
    {
      name: 'System configuration tools',
      desc: 'Advanced tools for system-level configuration management',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    }
  ],
  'AGENT MANAGEMENT': [
    {
      name: 'Agent overview and detail views',
      desc: 'Comprehensive views for monitoring and managing agents',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Agent status toggling',
      desc: 'Interface for enabling/disabling agents and changing their status',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'S',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 2,
      effortRequired: 2
    },
    {
      name: 'Agent monitoring and management',
      desc: 'Tools for monitoring agent performance and managing their lifecycle',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Agent health tracking',
      desc: 'Monitor agent health status and performance metrics',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Other',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ],
  'RESPONSIVE DESIGN': [
    {
      name: 'Mobile-responsive layouts',
      desc: 'Responsive design that works seamlessly on mobile devices',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 4
    },
    {
      name: 'Adaptive sidebar behavior',
      desc: 'Sidebar that adapts to different screen sizes and orientations',
      moscow: 'Should-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Touch-friendly interfaces',
      desc: 'Interface elements optimized for touch interaction',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Cross-device compatibility',
      desc: 'Ensure consistent experience across different devices and browsers',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Reduce Churn by 5%',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ],
  'INTERACTIVE FEATURES': [
    {
      name: 'Drag and drop functionality',
      desc: 'React DnD implementation for interactive drag and drop operations',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Modal dialogs and overlays',
      desc: 'Comprehensive modal system for detailed views and interactions',
      moscow: 'Must-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Expandable components',
      desc: 'Components that can expand and collapse for better space utilization',
      moscow: 'Should-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'S',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 2,
      effortRequired: 2
    },
    {
      name: 'Interactive charts and graphs',
      desc: 'Highly interactive charts with zoom, pan, and selection capabilities',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'L',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 4,
      effortRequired: 4
    },
    {
      name: 'Context menus and dropdowns',
      desc: 'Rich context menu system for quick access to actions',
      moscow: 'Should-Have',
      targetQuarter: 'Q1 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ],
  'CHART ENHANCEMENTS': [
    {
      name: 'Smooth animations with configurable settings',
      desc: 'Chart animations with configurable duration and easing functions',
      moscow: 'Could-Have',
      targetQuarter: 'Q3 2026',
      tshirtSize: 'S',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 2
    },
    {
      name: 'Rollover tooltips on timestamps',
      desc: 'Interactive tooltips that appear when hovering over chart timestamps',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'S',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 3,
      technicalComplexity: 2,
      effortRequired: 2
    },
    {
      name: 'Expandable chart functionality',
      desc: 'Ability to expand charts into full-screen or modal views',
      moscow: 'Could-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'S',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 2,
      effortRequired: 2
    },
    {
      name: 'Modal view for detailed analysis',
      desc: 'Dedicated modal views for in-depth chart and data analysis',
      moscow: 'Could-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Increase NPS',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 2,
      technicalComplexity: 3,
      effortRequired: 3
    },
    {
      name: 'Real-time data updates with animation',
      desc: 'Live data updates with smooth animations to show changes',
      moscow: 'Should-Have',
      targetQuarter: 'Q2 2026',
      tshirtSize: 'M',
      state: 'Missing',
      goal: 'Improve Onboarding',
      gapTypes: ['Technology/Tech Debt'],
      workflowStatus: 'Planning',
      businessValue: 4,
      technicalComplexity: 3,
      effortRequired: 3
    }
  ]
};
